config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  resource :dashboard, only: [:show]  
  get 'dashboard/:slug/decks', to: 'decks#index', as: "dashboard_deck"

  resource :session, only: [:destroy]
  resources :fclasses
  resources :decks, only: [:index, :create, :destroy]
  get 'dashboard/:slug/decks/:id', to: 'decks#show', as: 'deck_study'
  resources :cards, only: [:create]
  get ':slug/decks/:id/edit', to: 'decks#edit', as: "edit_deck"
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'

  root "dashboards#show"
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  mount_uploaders :images, CardUploader
  validates :question, presence: true
  validates :answer, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  validates :title, presence: true
  has_many :cards
end

app/models/fclass.rb
class Fclass < ApplicationRecord
  extend FriendlyId

  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      [:title, :user_id]
    ]
  end

  mount_uploader :class_img, FclassUploader
  belongs_to :user

  validates :title, presence: true
  has_many :decks
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, 
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
    uniqueness: true
  validates :password, length: { minimum: 6 }

  has_many :fclasses
end

app/controllers/application_controller.rb
require 'pry'
class ApplicationController < ActionController::Base
  before_action :check_signin
  def index
    
  end
  private
  def check_signin
    redirect_to signin_path if !helpers.current_user
  end
end

app/controllers/cards_controller.rb
require 'pry'
class CardsController < ApplicationController
  def modal
    f = helpers.form_with(model: @card)
    render partial: 'cards/modal', locals: {f: f}
  end

  def create 
    deck = Deck.find(params[:deck_id])
    new_questions = []
    new_answers = []

    update_questions = []
    update_answers = []

    delete_questions = []
    delete_answers = []
    params.each do |param, value|
      next if value.blank?
      if param.starts_with?("question")
        if param.include?("new")
          new_questions << value 
        elsif param.include?("delete")
          delete_questions << value
        else
          card_id = param.split("-").last
          update_questions << { "#{card_id}": value}
        end
      elsif param.starts_with?("answer")
        if param.include?("new")
          new_answers << value 
        elsif param.include?("delete")
          delete_answers << value
        else
          update_answers << value
        end
      end
    end
    # Create new card
    0.upto(new_questions.size-1) do |i|
      card = deck.cards.build(question: new_questions[i], answer: new_answers[i])
      card.save
    end
    # Update old cards
    0.upto(update_questions.size-1) do |i|
      card_id = update_questions[i].keys[0]
      card = Card.find(card_id.to_s)
      card.update(question: update_questions[i][card_id], answer: update_answers[i])
    end
    # Delete cards
    0.upto(delete_questions.size-1) do |i|
      Card.destroy_by(question: delete_questions[i], answer: delete_answers[i])
    end
    redirect_to dashboard_deck_path(Fclass.friendly.find(deck.fclass_id))
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = helpers.current_user
  end
end

app/controllers/decks_controller.rb
require 'pry'
class DecksController < ApplicationController
  def index
    @user = User.find(params[:slug].split('-').last)
    @fclass = Fclass.friendly.find(params[:slug])
    @decks = @fclass.decks
  end

  def show
    @user = User.find(params[:slug].split('-').last)
    @fclass = Fclass.friendly.find(params[:slug])
    @deck = Deck.find(params[:id]) 
    @cards = @deck.cards
  end

  def edit
    @deck = Deck.find(params[:id])
    @fclass = Fclass.friendly.find(@deck.fclass_id)
    @user = User.find(@fclass.user_id)
  end

  def create
    fclass = Fclass.friendly.find(params[:slug])
    deck = fclass.decks.build(title: params[:deck_title])
    if deck.save 
      redirect_to request.referrer
    else
    end
  end

  def destroy
    deck = Deck.find(params[:id])
    deck.destroy 
    redirect_to request.referrer
  end
end

app/controllers/fclasses_controller.rb
require 'pry'
class FclassesController < ApplicationController
  def create
    fclass = helpers.current_user.fclasses.build(title: params[:class_title])
    if fclass.save 
      #Popup message 
      redirect_to request.referrer
    else
      # Popup message
    end
  end

  def update
    fclass = Fclass.friendly.find(params[:id])
    fclass.class_img = params[:fclass][:class_img]
    fclass.save
    redirect_to request.referrer
  end

  private
  def fclass_params
    params.require(:fclass).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_signin

  def new
      
  end

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash[:alert] = "Invalid username or password!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_signin
  def new
    @user = User.new
  end

  def create 
    @user = User.create(signup_params)
    if @user.save 
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def signup_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def active_fclass?(fclass_title)
    "#{fclass_title.downcase.gsub(' ', '-')}-#{current_user.id}" == params[:slug]
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/fclasses_helper.rb
module FclassesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_modal.html.erb
<div class="flex flex-col md:flex-row w-full border-2 border-slate-400 focus-within:border-emerald-500 rounded-lg px-4 py-2" data-card-target="modal">
  <div class="flex items-center flex-1 border-b-2 md:border-b-0 md:border-e-4 border-slate-200 md:me-2 w-full">
    <span class="text-slate-400 font-semibold text-2xl">Q</span>
    <%= f.text_area :question, id: "question-#{id ? id : 'new'}", name: "question-#{id ? id : 'new'}",
      value: question, class: 'h-10 md:h-8 w-full border-none focus:ring-0', placeholder: 'Question', data: {card_target: 'textarea'} %>
  </div>
  <div class="flex items-center flex-1 w-full">
    <span class="text-slate-400 font-semibold text-2xl">A</span>
    <%= f.text_area :answer, id: "answer-#{id ? id : 'new'}", name: "answer-#{id ? id : 'new'}",
      value: answer, class: 'h-10 md:h-8 w-full border-none focus:ring-0', placeholder: 'Answer', data: {card_target: 'textarea'} %>
  </div>
</div>
<div class="text-2xl md:hidden md:text-xl group-hover:block cursor-pointer" data-action="click->card#delete">
  <i class="fa-solid fa-xmark"></i>
</div>

app/views/dashboards/_modal.html.erb
<div class="hidden fixed top-0 bottom-0 left-0 right-0 bg-slate-950 opacity-70 z-40" data-dashboard-target="overlay" data-action="click->dashboard#hide">
</div>

<div class="hidden fixed bg-white z-50 top-56 text-center p-2 py-6 rounded-xl left-6 right-6 md:left-1/3 md:right-1/3" data-dashboard-target="modal">
  <div class="absolute top-2 right-4 cursor-pointer text-xl text-slate-400 hover:text-slate-900" data-action="click->dashboard#hide">
    <i class="fa-solid fa-xmark"></i>
  </div>
  <div class="font-bold text-xl text-emerald-500">
    Create New Class
  </div>
  <p class="font-semibold mb-2">A Class is set of Flashcards, grouped into Decks</p>
  <%= form_with(url: "/fclasses", html: {class: 'flex flex-col items-center gap-2'}) do |f|%>
    <%= f.text_field :class_title, autofocus: true, placeholder: 'Class title', class:"rounded-md focus:ring-0 border-2 border-slate-400 focus:border-emerald-500" %>
    <%= f.submit "Create", class: "cursor-pointer bg-emerald-500 hover:bg-emerald-600 w-fit text-white font-semibold px-2 py-1 rounded-md" %>
  <% end %>
</div>

app/views/dashboards/show.html.erb
<div class="md:flex gap-4" data-controller="dashboard">
  <%= render 'shared/sidebar' %>
  <div class="mx-auto mt-56 text-center text-slate-900 md:p-2 z-0">
    <div class="mx-2">
      <% if @user.fclasses.size == 0 %>
        <h1 class="text-xl md:text-3xl font-semibold">Your library is empty</h1>
        <div class="text-slate-400 text-2xl md:text-2xl w-fit font-bold flex items-center mt-4 cursor-pointer hover:text-slate-600 gap-2">
          <i class="fa-solid fa-circle-plus"></i>
          <span class="text-xl underline" data-action="click->dashboard#show">Create new class to start learning now</span>
        </div>
      <% else %>
        <h1 class="text-xl md:text-3xl font-semibold">Start studying now</h1>
        <div class="text-2xl md:text-2xl w-fit font-bold flex items-center mt-4 text-slate-600 gap-2">
          <span class="text-xl">Pick your favorite class to start</span>
        </div>
      <% end %>
    </div>
  </div>
  <%= render 'dashboards/modal' %>
</div>

app/views/decks/_deck_card.html.erb
<div class="flex text-xl h-12 items-center hover:bg-slate-300 px-4 cursor-pointer mt-2 rounded-md odd:bg-slate-100">
  <div>
    <h3 class=""><%= deck.title %></h3>
  </div>
  <div class="ms-auto hidden md:flex gap-4 md:gap-2 items-center text-2xl">
    <%= button_to deck_path(deck), method: :delete, form: {data: {turbo_confirm: 'Are you sure you want to delete this deck?'}} do %> 
      <i class="fa-solid fa-trash-can text-red-500 hover:text-red-700"></i>
    <% end %>
    <%= link_to edit_deck_path(fclass, deck) do %> 
      <i class="fa-solid fa-pen text-emerald-500 hover:text-emerald-700"></i>
    <% end %>
    <% if deck.cards.size != 0 %>
      <%= link_to deck_study_path(fclass, deck) do %>
        <i class="fa-solid fa-circle-play text-blue-500 hover:text-blue-700"></i>
      <% end %>
    <% else %>
        <i class="fa-solid fa-circle-play text-zinc-500 hover:text-zinc-600"></i>
    <% end %>
  </div>
  <div class="ms-auto md:hidden text-2xl">
    <i class="fa-solid fa-ellipsis" data-action="click->deck#show_option" data-deck-id-value=<%= deck.id %>></i>
  </div>
</div>

app/views/decks/_deck_header.html.erb
<div class="flex gap-2 md:gap-6 items-center">
  <%= form_with model: @fclass do |f| %>
    <div class="w-40 h-40 relative group text-6xl md:text-7xl border-2 border-transparent hover:border-slate-600 rounded-xl cursor-pointer p-4 flex justify-center items-center"
    onclick="document.getElementById('class_img').click()">
      <% if fclass.class_img.file.nil? %>
        <i class="fa-solid fa-clone text-zinc-900"></i>
      <% else %>
        <%= image_tag fclass.class_img.url, class: 'w-full h-full rounded-md shadow-lg shadow-slate-900/50' %>
      <% end %>
      <span class="absolute hidden group-hover:block text-base bg-slate-600 text-slate-400 text-center p-1 -bottom-4 -right-4 rounded-full w-8 h-8">
        <i class="fa-regular fa-pen-to-square hover:text-slate-300"></i>
      </span>
    </div>
    <%= f.file_field :class_img, id:'class_img', class: 'hidden', onchange: 'this.form.submit()'%>
  <% end %>
  <div class="flex flex-col text-xl text-zinc-900 font-bold">
    <h2 class="text-2xl"><%= fclass.title %></h2>
    <p class="font-semibold text-base">Creator: <span><%= user.username %></span></p>
    <%= button_to "Study", "", class: "text-lg bg-zinc-500 text-slate-300 w-32 md:w-56 rounded-2xl mt-2" %>
  </div>
  <div class="ms-auto">
    <button>Delete Deck</button>
  </div>
</div>

app/views/decks/_deck_option.html.erb
<div class="hidden fixed top-0 bottom-0 left-0 right-0 bg-slate-950 opacity-70 z-40" data-deck-target="optionoverlay" data-action="click->deck#hide">
</div>

<div class="hidden fixed bg-white z-50 top-56 text-center p-2 py-6 rounded-xl left-6 right-6 md:left-1/3 md:right-1/3" data-deck-target="option" 
  data-deck-id-value=<%= deck.id %>>
  <div class="absolute top-2 right-4 cursor-pointer text-xl text-slate-400 hover:text-slate-900" data-action="click->deck#hide_option" 
    data-deck-id-value=<%= deck.id %>>
    <i class="fa-solid fa-xmark"></i>
  </div>
  <%= deck.title %>
  <div class="font-bold text-xl text-emerald-500">
    Deck Options 
    <div class="mt-2 flex flex-col w-3/4 gap-3 mx-auto text-lg">
      <%= link_to deck_study_path(fclass, deck), class:"grid grid-cols-4 items-center bg-blue-500 text-white px-4 py-2 rounded-lg w-full" do %> 
        <i class="fa-solid fa-circle-play"></i>
        <span class="col-span-3 text-left">Start studying</span>
      <% end %>
      <%= link_to edit_deck_path(fclass, deck), class:"grid grid-cols-4 items-center bg-emerald-500 text-white px-4 py-2 rounded-lg w-full" do %> 
        <i class="fa-solid fa-pen"></i>
        <span class="col-span-3 text-left">Edit deck</span>
      <% end %>
      <%= button_to deck_path(deck), method: :delete, id: deck.id, class:"grid grid-cols-4 items-center bg-red-500 text-white px-4 py-2 rounded-lg w-full" do %> 
        <i class="fa-solid fa-trash-can"></i>
        <span class="col-span-3 text-left">Delete deck</span>
      <% end %>
    </div>
  </div>
</div>

app/views/decks/_modal.html.erb
<div class="hidden fixed top-0 bottom-0 left-0 right-0 bg-slate-950 opacity-70 z-40" data-deck-target="overlay" data-action="click->deck#hide">
</div>

<div class="hidden fixed bg-white z-50 top-56 text-center p-2 py-6 rounded-xl left-6 right-6 md:left-1/3 md:right-1/3" data-deck-target="modal">
  <div class="absolute top-2 right-4 cursor-pointer text-xl text-slate-400 hover:text-slate-900" data-action="click->deck#hide">
    <i class="fa-solid fa-xmark"></i>
  </div>
  <div class="font-bold text-xl text-emerald-500">
    Create New Deck
  </div>
  <p class="font-semibold mb-2">A Deck contains multiple cards of same topic</p>
  <%= form_with(url: "/decks", html: {class: 'flex flex-col items-center gap-2'}) do |f|%>
    <%= f.hidden_field :slug, value: params[:slug] %>
    <%= f.text_field :deck_title, autofocus: true, placeholder: 'Deck title', class:"rounded-md focus:ring-0 border-2 border-slate-400 focus:border-emerald-500" %>
    <%= f.submit "Create", class: "cursor-pointer bg-emerald-500 hover:bg-emerald-600 w-fit text-white font-semibold px-2 py-1 rounded-md" %>
  <% end %>
</div>

app/views/decks/_study_card.html.erb
<div class="hidden h-fit no-scrollbar overflow-auto mt-28 mx-auto w-fit text-2xl md:text-4xl text-center" data-study-target="question">
  <p>
    <%= card.question %>
  </p>
</div>
<div class="hidden h-fit no-scrollbar overflow-auto mt-28 mx-auto w-fit text-2xl md:text-4xl text-center" data-study-target="answer">
  <% card.answer.split("\n").each do |answer| %>
    <p class="text-left">
      <%= answer %>
    </p>
  <% end %>
</div>

app/views/decks/edit.html.erb
<div class="md:flex gap-4 z-20" data-controller="dashboard card">
  <%= render 'shared/sidebar' %>
  <div class="relative mx-2 md:mx-10 mt-4 text-slate-900 md:p-2 z-20 font-semibold" style="width:95%">
    <%= render 'deck_header', fclass: @fclass, user: @user %>
    <div class="flex justify-between border-b-2 border-slate-500">
      <h2 class="text-md md:text-xl w-full">Deck: <span class="text-emerald-500 z-10"><%= @deck.title %></span> - <%= @deck.cards.size %> 
    <%= "card".pluralize(@deck.cards.size) %></h2>
      <button class="bg-emerald-500 hover:bg-emerald-600 text-white font-semibold text-lg px-4 py-1 rounded-lg mb-2" data-action="click->card#submit" >
        Save
      </button>
    </div>
    <div class="w-full no-scrollbar mt-2 overflow-auto" id="card-container">
      <%= form_with(url: '/cards', html: {class: 'flex flex-col items-center w-full gap-2'}, 
                    data: {card_target: 'form'}) do |f| %>
        <%= f.hidden_field :deck_id, value: params[:id] %>
        <% @deck.cards.each do |card| %>
          <div class="flex w-full items-center gap-2 group">
            <%= render 'cards/modal', f:f, question: card.question, answer: card.answer, id: card.id %>
          </div>
        <% end %>
        <div class="flex w-full items-center gap-2 group">
          <%= render 'cards/modal', f: f, question: nil, answer: nil, id: nil %>
        </div>
      <% end %>
    </div>
    <div class="text-slate-600 md:text-slate-400 text-2xl md:text-2xl w-fit font-bold flex items-center my-4 cursor-pointer hover:text-slate-600 gap-2" 
      data-action="click->card#add">
      <i class="fa-solid fa-circle-plus"></i>
      <span class="text-lg">Create new card</span>
    </div>
  </div>
  <%= render 'dashboards/modal' %>
</div>

app/views/decks/index.html.erb
<div class="md:flex gap-4 z-20" data-controller="dashboard deck">
  <%= render 'shared/sidebar' %>
  <div class="relative mx-2 md:mx-10 mt-4 text-slate-900 md:p-2 z-20 font-semibold" style="width:95%">
    <%= render 'deck_header', fclass: @fclass, user: @user %>
    <h2 class="text-xl w-full border-b-2 border-slate-500">My decks (<span><%= @fclass.decks.size %></span>)</h2>
    <div>
    </div>
    <div class="w-11/12 md:w-full mx-auto">
      <% @decks.each do |deck| %>
        <%= render 'decks/deck_card', deck: deck, fclass: @fclass %>
        <%= render 'decks/deck_option', deck: deck, fclass: @fclass %>
      <% end %>
    </div>
    <div class="text-slate-600 md:text-slate-400 text-2xl md:text-2xl w-fit font-bold flex items-center my-4 cursor-pointer hover:text-slate-600 gap-2" 
      data-action="click->deck#show">
      <i class="fa-solid fa-circle-plus"></i>
      <span class="text-lg" data-sidebar-target="content">Create new deck</span>
    </div>
  </div>
  <%= render 'decks/modal' %>
  <%= render 'dashboards/modal' %>
</div>

app/views/decks/show.html.erb
<div class="md:flex gap-4 z-20" style="height:90%" data-controller="study" data-study-size=<%= @cards.size %>>
  <div class="relative md:mx-10 mt-4 text-slate-900 md:p-2 z-20 font-semibold w-full h-full flex flex-col items-center">
    <div class="flex items-center gap-4 px-2 w-full">
      <%= link_to "Back", dashboard_deck_path(@fclass), class:"bg-emerald-500 hover:bg-emerald-600 text-white font-semibold text-md px-4 py-1 rounded-lg" %>
      <h2 class="text-slate-500">Deck: <span class="text-emerald-500"><%= @deck.title %></span></h2>
      <h2 class="text-slate-500">Card: <span class="text-emerald-500"><span data-study-target="current">1</span>/<%= @cards.size %></span></h2>
    </div>
    <div class="w-10/12 md:w-7/12 flex-1 border-2 border-slate-500 mt-10 rounded-lg">
      <div class="w-full h-8 bg-slate-500">
      </div>
      <div class="h-32 md:h-96 px-2 md:px-4">
        <div class="font-semibold text-3xl text-slate-400 mt-2" data-study-target="state">Q</div>
        <% @cards.each do |card| %>
          <%= render 'study_card', card: card %>
        <% end %>
      </div>
    </div>
    <div class="w-fit mt-4">
      <button class="px-4 py-2 bg-slate-500 hover:bg-slate-600 text-slate-200 font-semibold rounded-lg" data-action="click->study#previous">Previous</button>
      <button class="px-4 py-2 bg-slate-500 hover:bg-slate-600 text-slate-200 font-semibold rounded-lg" data-action="click->study#reveal">Reveal answer</button>
      <button class="px-4 py-2 bg-slate-500 hover:bg-slate-600 text-slate-200 font-semibold rounded-lg" data-action="click->study#next">Next</button>
    </div>
  </div>
</div>

app/views/fclasses/_sidebar_title.html.erb
<div class="w-full flex justify-center cursor-pointer">
  <%= link_to dashboard_deck_path("#{fclass.title.downcase.gsub(' ', '-')}-#{current_user.id}"),
    class: "text-5xl md:text-3xl #{active_fclass?(fclass.title) ? 'text-emerald-500 hover:text-emerald-600' : 'text-slate-400 hover:text-slate-500'} flex items-center justify-center gap-2 w-3/4 my-1 group" do %>
    <div class="w-16 h-16 flex items-center justify-center">
      <% if fclass.class_img.file.nil? %> 
        <i class="fa-solid fa-clone"></i>
      <% else %>
        <%= image_tag fclass.class_img.url, class: " w-full h-full rounded-md #{active_fclass?(fclass.title) ? 'border-2 border-emerald-500' : ''}" %>
      <% end %>
    </div>
    <span class="#{mobile ? '' : 'hidden'} text-xl ms-auto w-3/4 font-semibold" data-sidebar-target="fclass"><%= fclass.title %></span>
    <span class="absolute hidden -right-2 shadow-lg shadow-slate-900/50 translate-x-full w-48 px-2 py-1 
    bg-zinc-800 rounded-lg text-slate-400 text-sm font-semibold" data-sidebar-target="prompt"><%= fclass.title %></span>
  <% end %>
  <!-- <span class="absolute opacity-0 group-hover:opacity-100 text-center text-slate-400 font-semibold z-50 bg-slate-950 w-fit"><%= fclass.title %></span> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashlib</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <main class="h-screen select-none overflow-hidden">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_sidebar.html.erb
<div class="relative md:hidden w-full h-12 bg-zinc-800 text-2xl z-30" data-controller="mobile">
  <div class="flex items-center justify-between px-4 h-full text-slate-400">
    <div class="flex gap-2 items-center">
      <i class="fa-solid fa-circle-user"></i>
      <h2 class="font-semibold"><%= @user.username %></h2>
    </div>
    <i class="fa-solid fa-bars" data-action="click->mobile#toggle"></i>
  </div>
  <div class="w-0 h-screen bg-zinc-800 duration-300 z-20" data-mobile-target="sidebar">
    <div class="hidden py-2 px-6 flex-col" style="height: 92%" data-mobile-target="content">
      <div class="text-slate-400 text-2xl md:text-2xl w-fit font-bold flex items-center my-4 cursor-pointer hover:text-slate-500 gap-2" 
        data-action="click->dashboard#show">
        <i class="fa-solid fa-circle-plus"></i>
        <span class="text-lg" data-sidebar-target="content">Create new class</span>
      </div>
      <p class="text-lg text-slate-400 font-bold w-full mb-2">
        My classes <span>(<%= @user.fclasses.size %>)</span>
      </p>
      <div class="flex flex-col gap-4 ">
        <% @user.fclasses.each do |fclass| %>
            <%= render 'fclasses/sidebar_title', fclass: fclass, mobile: true %>
        <% end %>
      </div>
      <%= link_to session_path, data: {turbo_method: :delete}, class:"text-red-700 md:text-slate-400 text-3xl md:text-2xl w-fit font-bold flex items-center 
        hover:text-red-700 gap-2 mt-auto " do %>
        <i class="fa-solid fa-arrow-right-from-bracket"></i>
        <span class="text-xl">Sign out</span>
      <% end %>
    </div>
  </div>
</div>
<div class="relative md:h-screen hidden w-full md:w-28 bg-zinc-800 md:flex flex-col items-center py-8 gap-2 duration-300 z-30" 
  data-controller="sidebar" data-sidebar-target="sidebar">
  <div class="text-slate-400 text-5xl w-fit font-bold flex flex-col items-center ">
    <i class="fa-solid fa-circle-user"></i>
    <p class="hidden text-xl mt-2" data-sidebar-target="content"><%= @user.username %></p>
  </div>
  <div class="text-slate-400 text-3xl md:text-2xl w-fit font-bold flex items-center mt-4 cursor-pointer hover:text-slate-500 gap-2" 
    data-action="click->dashboard#show">
    <i class="fa-solid fa-circle-plus"></i>
    <span class="hidden text-xl" data-sidebar-target="content">Create new class</span>
  </div>
  <p class="hidden text-lg text-slate-400 font-bold w-full px-4 mt-2" data-sidebar-target="content">
    My classes <span>(<%= @user.fclasses.size %>)</span>
  </p>
  <div class="mt-4 w-full h-full overflow-x-hidden overflow-y-auto flex flex-col gap-2 items-center">
    <% @user.fclasses.each do |fclass| %>
      <%= render 'fclasses/sidebar_title', fclass: fclass %>
    <% end %>
  </div>
  <div class="w-10 h-10 absolute top-10 -right-5 rounded-full text-slate-400 flex justify-center items-center 
    bg-zinc-900 border-2 border-slate-400 cursor-pointer" data-sidebar-target="expand" data-action="click->sidebar#expand">
    <i class="fa-solid fa-angles-right"></i>
  </div>
  <div class="w-10 h-10 absolute top-10 -right-5 rounded-full text-slate-400 hidden justify-center items-center 
    bg-zinc-900 border-2 border-slate-400 cursor-pointer " data-sidebar-target="shrink" data-action="click->sidebar#shrink">
    <i class="fa-solid fa-angles-left"></i>
  </div>
  <%= link_to session_path, data: {turbo_method: :delete}, class:"text-slate-400 text-3xl md:text-2xl w-fit font-bold flex items-center 
    cursor-pointer hover:text-red-700 gap-2 mt-auto" do %>
    <i class="fa-solid fa-arrow-right-from-bracket"></i>
    <span class="hidden text-xl" data-sidebar-target="content">Sign out</span>
  <% end %>
</div>